CREATE SCHEMA `cdb2-dev` DEFAULT CHARACTER SET utf8 ;
CREATE TABLE admin_area_subdivision_major (id BIGINT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, created_by BIGINT, created_on DATETIME, deleted TINYINT(1) default 0, modified_by BIGINT, modified_on DATETIME, name VARCHAR(255) NOT NULL, PRIMARY KEY (id));
CREATE TABLE admin_area_subdivision_middle (id BIGINT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, created_by BIGINT, created_on DATETIME, deleted TINYINT(1) default 0, modified_by BIGINT, modified_on DATETIME, name VARCHAR(255) NOT NULL, admin_area_subdivision_major BIGINT, PRIMARY KEY (id));
CREATE TABLE admin_area_subdivision_minor (id BIGINT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, created_by BIGINT, created_on DATETIME, deleted TINYINT(1) default 0, modified_by BIGINT, modified_on DATETIME, name VARCHAR(255) NOT NULL, admin_area_subdivision_middle BIGINT, PRIMARY KEY (id));
CREATE TABLE municipality (id BIGINT AUTO_INCREMENT NOT NULL, created_by BIGINT, created_on DATETIME, deleted TINYINT(1) default 0, latitude VARCHAR(255), longitude VARCHAR(255), modified_by BIGINT, modified_on DATETIME, name VARCHAR(255) NOT NULL, postal_code VARCHAR(255) NOT NULL, admin_area_subdivision_major BIGINT, admin_area_subdivision_middle BIGINT, admin_area_subdivision_minor BIGINT, PRIMARY KEY (id));
ALTER TABLE admin_area_subdivision_middle ADD CONSTRAINT dminareasubdivisionmiddleadminareasubdivisionmajor FOREIGN KEY (admin_area_subdivision_major) REFERENCES admin_area_subdivision_major (id);
ALTER TABLE admin_area_subdivision_minor ADD CONSTRAINT dminareasubdivisionminoradminareasubdivisionmiddle FOREIGN KEY (admin_area_subdivision_middle) REFERENCES admin_area_subdivision_middle (id);
ALTER TABLE municipality ADD CONSTRAINT FK_municipality_admin_area_subdivision_middle FOREIGN KEY (admin_area_subdivision_middle) REFERENCES admin_area_subdivision_middle (id);
ALTER TABLE municipality ADD CONSTRAINT FK_municipality_admin_area_subdivision_major FOREIGN KEY (admin_area_subdivision_major) REFERENCES admin_area_subdivision_major (id);
ALTER TABLE municipality ADD CONSTRAINT FK_municipality_admin_area_subdivision_minor FOREIGN KEY (admin_area_subdivision_minor) REFERENCES admin_area_subdivision_minor (id);
ALTER TABLE admin_area_subdivision_major ADD INDEX `idx_code_major` (`code` ASC);
ALTER TABLE admin_area_subdivision_middle ADD INDEX `idx_code_middle` (`code` ASC);
ALTER TABLE admin_area_subdivision_minor ADD INDEX `idx_code_minor` (`code` ASC);
ALTER TABLE municipality ADD INDEX `idx_code_municipality` (`postal_code` ASC);